<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE headless [
        <!ENTITY outputDir "const(THIS_FILE)/target/structure101-reports">
        <!ENTITY projectName "Maven">
        <!ELEMENT headless (operations|arguments)*>
        <!ELEMENT operations (operation)*>
        <!ELEMENT operation (argument)*>
        <!ATTLIST operation
                type CDATA #REQUIRED>
        <!ELEMENT argument (override)*>
        <!ATTLIST argument
                name CDATA #REQUIRED
                value CDATA #REQUIRED>
        <!ELEMENT arguments (argument)*>
        <!ELEMENT override (classpathentry)*>
        <!ATTLIST override
                attribute CDATA #REQUIRED>
        <!ELEMENT classpathentry (#PCDATA)>
        <!ATTLIST classpathentry
                kind CDATA #REQUIRED
                module CDATA #REQUIRED
                path CDATA #REQUIRED>
        ]>
<headless>
    <operations>

        <!-- check key measure increase -->
        <operation type="report-key-measures">
            <argument name="output-file" value="&outputDir;/key-measures.xml"/>
        </operation>

        <!-- publish snapshot and diagrams -->
        <operation type="publish">
            <argument name="label" value="LABEL_TOKEN"/>
            <argument name="overwrite" value="false"/>
            <argument name="diagrams" value="true"/>
            <argument name="spec" value="true"/>
            <argument name="actions" value="true"/>
        </operation>

        <!-- check actions to show those that can't be applied - ie they are already applied or other changes have made them obsolete -->
        <operation type="check-actions">
            <argument name="output-dir" value="&outputDir;"/>
        </operation>

        <!-- report summary for the project snapshot -->
        <operation type="report-summary">
            <argument name="output-dir" value="&outputDir;"/>
            <argument name="xml" value="true"/>
            <argument name="notips" value="true"/>
            <argument name="overwrite" value="true"/>
            <argument name="name" value="&projectName;"/>
        </operation>
    </operations>

    <arguments>
        <argument name="local-project" value="const(THIS_FILE)/structure101-settings.java.hsp">
        </argument>
        <argument name="repository" value="http://ubuntu-server:8989/s101j/data"/>
        <argument name="project" value="&projectName;"/>
    </arguments>
</headless>
